aws:
  accessKeyId:
  region:
  secretAccessKey:
  secretName:

env: dev
image:
  name: thehubpub
  repository: jalgraves/thehubpub
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

istio:
  enabled: false

containerPort: 3037
portName: tcp-thehubpub

regionCode:
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    memory: 1Gi
