apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thehubpub.fullname" . }}
  labels: {{ include "thehubpub.labels" . | nindent 4 }}

spec:
  progressDeadlineSeconds: 300
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels: {{ include "thehubpub.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "thehubpub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: {{ .Values.logLevel | default "dev" }}
        {{- if .Values.externalSecrets.enabled }}
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: API_USERNAME
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: API_PASSWORD
        - name: MENU_API_PROTOCOL
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: MENU_API_PROTOCOL
        - name: MENU_API_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: MENU_API_PORT
        - name: MENU_API_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: MENU_API_HOST
        - name: MERCH_API_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: MERCH_API_HOST
        - name: MERCH_API_PROTOCOL
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: MERCH_API_PROTOCOL
        - name: MERCH_API_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: MERCH_API_PORT
        - name: CONTACT_API_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: CONTACT_API_HOST
        - name: CONTACT_API_PROTOCOL
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: CONTACT_API_PROTOCOL
        - name: CONTACT_API_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "thehubpub.fullname" . }}
              key: CONTACT_API_PORT
        {{- end }}
      {{- if eq .Values.env "dev" }}
        image: "{{ .Values.image.name}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Never
      {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
      {{- end }}
        name: hubpub
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: {{ include "thehubpub.targetPort" . }}
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        resources: {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - cat
            - /app/package.json
          initialDelaySeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ include "thehubpub.targetPort" . }}
          initialDelaySeconds: 15
          failureThreshold: 3
          periodSeconds: 10
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "thehubpub.serviceAccountName" . }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
